### ISSUE TITLE
Create a CAVATICA OPC rnaseq-batch-correct module app

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/OpenPBTA-analysis#394]
# ✨

#### [Required] Is this a new tool/workflow?
- Yes

#### Provide software links and `dockerPull` location if applicable
- the `rnaseq-batch-correct` module scripts and documentation here:
   - https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/rnaseq-batch-correct/analyses/rnaseq-batch-correct
- needs to wait until after [PR d3b-center/ticket-tracker-OPC#247](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/247) has been approved and merged. 

#### Add reference files and test input locations if applicable
- all parameters, inputs, outputs, and software dependencies  described in the [rnaseq-batch-correct module README](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/README.md)

Inputs:
- Raw counts or RSEM expected counts file
- Housekeeping gene atlas negative control gene list - located in module under `input` (described in readme), simple RDS file containing HGNC gene symbols. 
- Positive control gene list - located in module under `input`. This consists of cell cycle regulatory genes described in readme. Simple list of HGNC symbols. 

Parameters: 
- k - denotes the number of singular values used in the matrix decomposition by RUVSeq (default: 5)
- d - drop parameter in RUVSeq which specifies the number of initial singular values to drop (default: 2 for tumor-normal comparisons)
- gtex-subgroups - comma-separated list of subgroups based on histology field (Tumor-Normal comparisons only)
- cancer_group_values - comma-separated list of cancer groups based on histology field
- dataset - user-defined name to assign for all output files

Outputs and software dependencies in readme. 
- all the module scripts include command-line options to enable easy implementation in CAVATICA

#### [Optional] How long do you think this work will take?
- For OPC v12 data release

#### [Optional] Who will complete this work?
- D3b bix-dev team

**Comment by aadamk** [comment]
ticket updated to describe key parameters and inputs.

**Comment by migbro** [comment]
So, is this being resurrected then @ewafula @jharenza ? Is it needed for v13, or more of a general goal?

**Comment by jharenza** [comment]
No, I just moved all tickets over to the new repo

**Comment by jharenza** [comment]
this is not prioritized
