### ISSUE TITLE
Updated analysis: Add WXS samples into `biospecimen_id_to_bed_map.tsv`

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/OpenPBTA-analysis#404]
#### What analysis module should be updated and why?
`biospecimen_id_to_bed_map.tsv` needs to be updated. 
https://github.com/d3b-center/OpenPedCan-analysis/issues/390

#### What changes need to be made? Please provide enough detail for another participant to make the update.
23 WXS samples from  
https://github.com/d3b-center/histologies-qc/blob/813921f237eba89968d7a674c415beff65afba98/output/2023-06-07_histologies-base.tsv
is missing in `biospecimen_id_to_bed_map.tsv`. The correlated bed files need to be provided.

The list of samples can be found in attachment. 
[missing_WXS.txt](https://github.com/d3b-center/OpenPedCan-analysis/files/11818615/missing_WXS.txt)

#### What input data should be used? Which data were used in the version being updated?
histologies file: https://github.com/d3b-center/histologies-qc/blob/813921f237eba89968d7a674c415beff65afba98/output/2023-06-07_histologies-base.tsv
`biospecimen_id_to_bed_map.tsv`

#### Who will complete the updated analysis?
@zhangb1  @jharenza

**Comment by zhangb1** [comment]
[20038D-17Q6-01.regions_padded100.bed.zip](https://github.com/d3b-center/OpenPedCan-analysis/files/11848985/20038D-17Q6-01.regions_padded100.bed.zip)
[S04380110_Padded.bed.zip](https://github.com/d3b-center/OpenPedCan-analysis/files/11848988/S04380110_Padded.bed.zip)

uploaded two padded files here , chordoma samples are all Tumor only samples,,, other 3 BS ID are from PNOC27, the region file is the same as PNOC008 from DGD

[mapped_to_region.txt](https://github.com/d3b-center/OpenPedCan-analysis/files/11849001/mapped_to_region.txt)


there are  four BS ID I can't find in our manifest, seems we never did the harmonization for them , @jharenza can you double check? 

```
BS_HA81ER6E
BS_P357W0ZG
BS_WJ89MPC5
BS_YFSRQ160
```

**Comment by jharenza** [comment]
there are no new WXS samples - @zzgeng I think there is an issue with the histologies file you were using and I have a new one, just updated this
