### ISSUE TITLE
Updated analysis: include H3 K28-mutant into LGG subtyping 

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/OpenPBTA-analysis#414]
#### What analysis module should be updated and why?
Update LGAT subtyping module to include H3 K28 mutant

#### What changes need to be made? Please provide enough detail for another participant to make the update.
include the detailed H3 mutant status into LGG subtyping

#### What input data should be used? Which data were used in the version being updated?
snv_maf.tsv.gz

#### Who will complete the updated analysis?
@zzgeng

**Comment by jharenza** [comment]
completed in #474
