### ISSUE TITLE
Transfer of consented DGD data to D3b s3

### ISSUE THREAD

**Issue by aadamk** [PediatricOpenTargets/OpenPBTA-analysis#416]
#### What data file(s) does this issue pertain to?

Files associated with C-ids for which `input_files_uploaded_to_s3` == FALSE (Matt's csv file attached below)

#### What release are you using?

NA

#### Put your question or report your issue here.

1. Transfer all CBTN consented DGD raw data files (.fastq, derived from participants confirmed as consented by DGD GC team) to d3b Frontier s3 bucket (s3://d3b-study-us-east-1-prd-sd-hkrzzhfw/Frontier/)
2. Pull associated clinical and sample metadata from FileMaker and Nexus. Fields of interest with associated data definitions are attached below. @jharenza - feel free to chime in here regarding any additional data fields/contents of interest for your team or that may be necessary for data registration by ADAPT (cc @nicholasvk, @baileyckelly). 

 
[approved_compt_and_rnasq.csv](https://github.com/d3b-center/OpenPedCan-analysis/files/12032550/approved_compt_and_rnasq.csv)
[CBTN_ClinicalManifest_Template.xlsx](https://github.com/d3b-center/OpenPedCan-analysis/files/12032572/CBTN_ClinicalManifest_Template.xlsx)
[CBTN_SampleManifest_Template_2.xlsx](https://github.com/d3b-center/OpenPedCan-analysis/files/12032574/CBTN_SampleManifest_Template_2.xlsx)

**Comment by luederm** [comment]
@aadamk the requested clinical data is not in FileMaker or Nexus. Not sure if this is something @nicholasvk could pull since he has experience pulling clinical data for GENIE?

**Comment by luederm** [comment]
The data may need to be pulled directly from EPIC

**Comment by jharenza** [comment]
@luederm can you append a column for `sample_type` to [approved_compt_and_rnasq.csv](https://github.com/d3b-center/OpenPedCan-analysis/files/12032550/approved_compt_and_rnasq.csv) - being Tumor or Normal? Thanks

**Comment by luederm** [comment]
@jharenza All COMPTs are tumor. Normal samples are COMPN but aren't included in the table. Here are the approved COMPN samples
[approved_compn.csv](https://github.com/d3b-center/OpenPedCan-analysis/files/12071442/approved_compn.csv)

**Comment by jharenza** [comment]
Ok great. For this ticket, can you add all remaining tumor _and_ normal files to s3, and list here all of the file paths, and we can separate the clinical info to a new ticket? Thanks!

**Comment by luederm** [comment]
Yes, sounds good

**Comment by nicholasvk** [comment]
@jharenza , @aadamk - The ADAPT team is working to develop processes to better track new files being added to D3b AWS storage so that we can monitor overall storage and associated costs. Is it possible to answer the following questions here in the ticket for the 313 new files being transferred into d3b-study-us-east-1-prd-sd-hkrzzhfw. For the transfer:

1) brief description of what it's for 2) who's funding the data generation 3) the number of samples 4) the estimated cost for compute and storage and then 5) the final actual costs of compute and storage

cc @baileyckelly , @allisonheath

**Comment by aadamk** [comment]
1. For processing DGD raw data through KF harmonized pipelines to include in OpenPedCan release + to use for precision medicine clinical reports (to include DGD data when selecting disease cohorts) 
2. CHOP Frontier funds are used for data generation and storage. 
3. @luederm - can you inform on the number of samples that correspond to these 313 files? 
4. @luederm or @zhangb1 - can you weigh in on estimated compute time and storage costs for this sample set? 
5. @luederm or @zhangb1 - same here when complete?

**Comment by jharenza** [comment]
To also chime in from our sprint planning meeting last week:
1. In addition to above by @aadamk, we will also use this T/N dataset as our panel cohort for tumor only benchmarking, which will be funded by 
2. strides/kids first

**Comment by luederm** [comment]
There are actually 313 samples to be transferred, so it would be 626 files (two fastqs each). I don't know what the storage costs will be but assuming it will be about 4GB per file, a rough estimate of new storage space used in the bucket would be 2.5TB. The transfer itself won't have any compute costs.

**Comment by luederm** [comment]
@baileyckelly, @allisonheath is this enough info?

**Comment by allisonheath** [comment]
Thanks for providing this - this is approved for transfer.

**Comment by luederm** [comment]
The transfer completed. Here are the locations of all COMPT, COMPN, and RNASQ fastqs in S3: [paired_ngs_panel_and_rnaseq_fastq_locations.csv](https://github.com/d3b-center/OpenPedCan-analysis/files/12194908/paired_ngs_panel_and_rnaseq_fastq_locations.csv)

**Comment by luederm** [comment]
@jharenza

**Comment by jharenza** [comment]
thanks so much!

**Comment by luederm** [comment]
Here are the locations of an additional 44 fastq files which failed to transfer previously due to not being in the Nexus test database: [additional_44_paired_ngs_panel_and_rnaseq_fastq_locations.csv](https://github.com/d3b-center/OpenPedCan-analysis/files/12197782/additional_44_paired_ngs_panel_and_rnaseq_fastq_locations.csv). There are on S3 now.
