### ISSUE TITLE
Updated analysis: merge cnv-consensus data

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/OpenPBTA-analysis#418]
#### What analysis module should be updated and why?
analysis/copy_number_consensus_call

#### What changes need to be made? Please provide enough detail for another participant to make the update.
merge `cnv-consensus_manta` with `cnv-consensus_gatk` to create the full cnv-consensus

#### What input data should be used? Which data were used in the version being updated?
`analysis/copy_number_consensus_call/results/cnv-consensus.seg.gz`
`analysis/copy_number_consensus_call_manta/results/cnv-consensus.seg.gz`

#### Who will complete the updated analysis?
@zzgeng

**Comment by jharenza** [comment]
completed in #419
