### ISSUE TITLE
Updated analysis: Typo in molecular_subtyping_HGG module

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/OpenPBTA-analysis#423]
#### What analysis module should be updated and why?
There is a tpyo in molecular_subtyping_HGG module 03 line 177
https://github.com/d3b-center/OpenPedCan-analysis/blob/dev/analyses/molecular-subtyping-HGG/03-HGG-molecular-subtyping-cnv.Rmd#L173C1-L178C78

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Fix the typo during data release process

#### Who will complete the updated analysis?
@zzgeng

**Comment by jharenza** [comment]
completed in #446
