### ISSUE TITLE
DGD consented panel file transfer (take 2)

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/OpenPBTA-analysis#427]
#### What data file(s) does this issue pertain to?
DGD DNA panels, all tests

#### Put your question or report your issue here.
Please transfer all consented DGD subjects' files to `d3b-study-us-east-1-prd-sd-hkrzzhfw under the path /sftp/dgd_raw_data` and update the manifest [here](https://d3b.atlassian.net/browse/D3B-39) to include all of the files.

Note: please also check whether all library preps for DNA were Sure Select XT or vary, so we can record that.

**Comment by jharenza** [comment]
cc @aadamk @baileyckelly @calkinsh

**Comment by luederm** [comment]
There are 538 fastq files to be transferred upon ADAPT approval

**Comment by jharenza** [comment]
completed
