### ISSUE TITLE
Updated analysis: include DGD fusion in LGG subtyping module

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/OpenPBTA-analysis#438]
#### What analysis module should be updated and why?
LGG subtyping module needs to be updated to include DGD fusion when molecular subtyping

#### What changes need to be made? Please provide enough detail for another participant to make the update.
DGD fusion should also be used in LGG subtyping.

#### What input data should be used? Which data were used in the version being updated?
fusion-dgd.tsv.gz

**Comment by jharenza** [comment]
this is included already
