### ISSUE TITLE
Updated analysis: include proteomic data for GitHub CI 

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/OpenPBTA-analysis#442]
#### What analysis module should be updated and why?
Include <s>miRNA and</s> proteomic data in `create-subset-files` for GitHub action. Since these matrices are small, will copy the whole file. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Update script in `create-subset-files` as well as GitHub workflow

#### What input data should be used? Which data were used in the version being updated?
miRNA and proteomic matrices.

**Comment by jharenza** [comment]
completed in #474
