### ISSUE TITLE
Updated analysis: Add PXA in HGG molecular subtyping

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/OpenPBTA-analysis#443]
#### What analysis module should be updated and why?
`molecular_subtype_HGG` needs to be updated to add Pleomorphic xanthoastrocytoma (PXA) subtype

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Based on WHO guidebook, PXA contains 
1. BRAF mutation or MAPK pathway gene alteration, 
2. combined with homozygous deletion of CDKN2A and/or CDKN2B. 
3. DNA methylation subclass as PXA

#### What input data should be used? Which data were used in the version being updated?
v12

**Comment by jharenza** [comment]
completed in #450
