### ISSUE TITLE
Updated analysis: Add H3 K28I mutation in DMG molecular subtyping

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/OpenPBTA-analysis#444]
#### What analysis module should be updated and why?
`molecular-subtyping-HGG` need to be updated to include H3 K28I mutation in molecular subtyping DMG.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Either H3 p.K28M or K28I can be used to identify DMG. Before we only included K28M. 

#### What input data should be used? Which data were used in the version being updated?
v12

#### Who will complete the updated analysis?
@zzgeng

**Comment by jharenza** [comment]
closed with #439
