### ISSUE TITLE
Updated analysis: Add Spine CNS region as a midline region in HGG subtyping

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/OpenPBTA-analysis#449]
#### What analysis module should be updated and why?
Module `molecular_subtype_HGG` needs to be updated 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Add Spine CNS region as a midline region in HGG subtyping

#### Who will complete the updated analysis?
@zzgeng

**Comment by jharenza** [comment]
We decided not to combine these.
