### ISSUE TITLE
Updated analysis: Update create-subset-files with coming HOPE data for v13

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/OpenPBTA-analysis#455]
#### What analysis module should be updated and why?
New data will be added for v13. `create-subset-files` need to be updated

#### What changes need to be made? Please provide enough detail for another participant to make the update.
SNV files from HOPE will be added for v13. add script to include new data in create-subset-files module.

#### What input data should be used? Which data were used in the version being updated?
SNV files from HOPE

**Comment by jharenza** [comment]
completed in #474
