### ISSUE TITLE
Updated analysis: EPN Molecular subtype module does not contain code for "EPN, SP"

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/OpenPBTA-analysis#468]
#### What analysis module should be updated and why?
EPN Molecular subtype
The script to assign `EPN, SP` has been removed. Need to investigate the reason 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Add the code to assign `EPN, SP` subtype to correlated samples

**Comment by jharenza** [comment]
closing, as we are using methyl to inform spinal
