### ISSUE TITLE
Updated analysis: Embryonal samples with different methylation subtype and molecular subtype 

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/OpenPBTA-analysis#470]
#### What analysis module should be updated and why?
molecular_subtyping_embryonal
For the samples with high confidence methylation classification as `ETMR_Atyp` and `CNS_BCOR_`, the final molecular subtype are not embryonal related subtype. These samples need to be examined and confirmed with the pathologist.

**Comment by jharenza** [comment]
https://github.com/rokitalab/OpenPedCan-Project/issues/24
