### ISSUE TITLE
Update TCGA/GTEX files for v13

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/OpenPBTA-analysis#475]
#### What data file(s) does this issue pertain to?
```
tcga-gene-expression-rsem-tpm-collapsed.rds --> tcga-gene-expression-rsem-tpm-collapsed.liftover.tsv.gz
tcga-gene-counts.liftover.tsv --> tcga-gene-counts.liftover.tsv.gz

gtex-gene-expression-rsem-tpm-collapsed.rds --> gtex-gene-expression-rsem-tpm-collapsed.liftover.tsv.gz
gtex-gene-counts.liftover.tsv --> gtex-gene-counts.liftover.tsv.gz
```

#### What release are you using?

v12 --> v13

#### Put your question or report your issue here.

Add TCGA counts, update names/gzip files

**Comment by zzgeng** [comment]
All the other files have been uploaded to s3. I did not see tcga counts file in s3. 

Also, by changing tcga file from rds to tsv.gz, code involved in tcga need to be updated, since before, gene name is in row names and now they are in `Gene_Symbol` column.

**Comment by jharenza** [comment]
Counts may not be in the bucket but in the separate cavatica project for the lift over, I'll check that later today if you don't have access. I'm not sure tcga is used in any modules right now, just gtex, but you do bring up a good point and maybe that's why the RDS was favored. We could keep the RDS (sorry). I was trying to think about users who might not use R... maybe we can discuss tomorrow.

**Comment by jharenza** [comment]
we are going to keep these in RDS, so closing
