### ISSUE TITLE
Updated analysis: Add EGFR as gene of interests in HGG molecular subtyping

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/OpenPBTA-analysis#532]
#### What analysis module should be updated and why?
Hgg molecular subtyping module

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Adding EGFR as gene of interests and EGFR mutation status for DMGs

**Comment by jharenza** [comment]
https://github.com/rokitalab/OpenPedCan-Project/issues/21
