### ISSUE TITLE
Add Methylation to LGAT subtyping chart

### ISSUE THREAD

**Issue by sickler-alex** [PediatricOpenTargets/OpenPBTA-analysis#533]
#### What data file(s) does this issue pertain to?

https://raw.githubusercontent.com/d3b-center/OpenPedCan-analysis/dev/analyses/molecular-subtyping-LGAT/plot/LGAT_subtyping_workflow.png

#### What release are you using?

None

#### Put your question or report your issue here.

Add methylation subytping to the LGAT subtyping flowchart.

**Comment by jharenza** [comment]
closed with #536
