### ISSUE TITLE
D3b Bix Dev Feature: Change Docker image

### ISSUE THREAD

**Issue by migbro** [PediatricOpenTargets/OpenPBTA-analysis#550]
# ✨

#### [Required] Is this a new tool/workflow?

No 

#### Provide software links and `dockerPull` location if applicable

analyses/collapse-rnaseq/cwl/tools/convert_to_rds.cwl

#### Add reference files and test input locations if applicable

Change `dockerPull: 'rocker/tidyverse:3.5.3'` to an image that has tidyverse and optparse already installed. Currently, wach yimt it runs, it installs it, but the install links are now out of date. Using one that does not need install is preferred, like: `pgc-images.sbgenomics.com/d3b-bixu/annofuse:0.92.0`

#### [Optional] How long do you think this work will take?

30 minutes - probably 29 to download the repo, 1 to fix

#### [Optional] Who will complete this work?

@migbro

**Comment by jharenza** [comment]
completed with #553
