### ISSUE TITLE
D3b Bix Dev Feature: Fix bug

### ISSUE THREAD

**Issue by migbro** [PediatricOpenTargets/OpenPBTA-analysis#552]
# ✨

#### [Required] Is this a new tool/workflow?

No

#### Provide software links and `dockerPull` location if applicable

analyses/collapse-rnaseq/cwl/scripts/liftover_collapse_rnaseq.py

#### Add reference files and test input locations if applicable

return happens too soon, causing all duplicate genes to be collapsed to be dropped, except one, in https://github.com/d3b-center/OpenPedCan-analysis/blob/a78b0e3fd711bcea2ed83fc0e950872a2065221b/analyses/collapse-rnaseq/cwl/scripts/liftover_collapse_rnaseq.py#L63-L71

#### [Optional] How long do you think this work will take?

an hour

#### [Optional] Who will complete this work?

@migbro

**Comment by jharenza** [comment]
completed with #553
