### ISSUE TITLE
👯‍♀️ Slightly duplicated RNA_library

### ISSUE THREAD

**Issue by migbro** [PediatricOpenTargets/OpenPBTA-analysis#562]
#### What data file(s) does this issue pertain to?

histologies.tsv

#### What release are you using?

v15

#### Put your question or report your issue here.

For `RNA_library`, the histologies file for v15 has both `exome_capture`  and `exome capture`.
Note the underscore in one and the space in the other

**Comment by jharenza** [comment]
Fix going in [here](https://github.com/d3b-center/histologies-qc/pull/13)

**Comment by jharenza** [comment]
https://github.com/rokitalab/OpenPedCan-Project/issues/16
