### ISSUE TITLE
Add unpaired normal BS IDs to OPC v16 histologies

### ISSUE THREAD

**Issue by rjcorb** [PediatricOpenTargets/OpenPBTA-analysis#598]
#### What data file(s) does this issue pertain to?

`histologies.tsv`
`histologies-base.tsv`

#### What release are you using?

v15

#### Put your question or report your issue here.

The following unpaired normal WGS and WXS IDs should be added to OPC V16 histologies files:

[bs-normal-to-add-opc-v16.txt](https://github.com/user-attachments/files/16163177/bs-normal-to-add-opc-v16.txt)

**Comment by jharenza** [comment]
now https://github.com/rokitalab/OpenPedCan-Project/issues/11
