### ISSUE TITLE
Updated analysis: fix MB SHH subtyping abridged output file 

### ISSUE THREAD

**Issue by rjcorb** [PediatricOpenTargets/OpenPBTA-analysis#599]
#### What analysis module should be updated and why?

`molecular-subtyping-MB` analysis module `05-subtype-mb-shh.R` script needs to be updated so that the `final_shh_subtype` column is added to abridged output `mb_shh_molecular_subtypes.tsv`, instead of the column `SHH_subtype` which only reports methylation-derived classifications

#### Who will complete the updated analysis?

@rjcorb

**Comment by jharenza** [comment]
closed with #599
