### ISSUE TITLE
Does GTEX data contain adults' tissue?

### ISSUE THREAD

**Issue by guodudou2** [PediatricOpenTargets/OpenPBTA-analysis#609]
#### What data file(s) does this issue pertain to?

GTEX

#### What release are you using?

V15

#### Put your question or report your issue here.
In this release, did you include all GTEX samples, or just use samples from kids? Thanks!

**Comment by jharenza** [comment]
Hi @guodudou2! The gtex file in this release contains all 17,382 RNA-Seq from GTEx v8 release. We lifted the gene symbols over to match our GENCODE (methods in the preprint [here](https://www.biorxiv.org/content/10.1101/2024.07.09.599086v1)).

We do have an ages file if you are curious to subset to only <40 (directly from the GTEx portal). 
[GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt](https://github.com/user-attachments/files/16964540/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt)


In the upcoming v16 release (TBD release date yet), we have gone and harmonized the GTEx rna-seq for all patients <40. If you are interested in specific files - gene TPM, isoform TPM, I can link them here for you!

**Comment by jharenza** [comment]
I am going to close this as resolved.

**Comment by guodudou2** [comment]
Thank you very much! It was very helpful. Sorry that I forgot to reply.
